#ภาระกิจที่ 5 รับค่าตัวเลข 5 ตัวแล้วแปลงตัวเลข 5 ตัวให้เป็นทศนิยมและจำนวนเชิงซ้อน
first_number=input('Enter your first number :')
second_number=input('Enter your second number :')
third_number=input('Enter your third number :')
fourth_number=input('Enter your fourth number :')
fifth_number=input('Enter your fifth number :')
print('float of '+first_number+' is ',float(first_number))
print('complex of '+first_number+' is',complex(first_number))
print('float of '+second_number+' is',float(second_number))
print('complex of '+second_number+' is',complex(second_number))
print('float of '+third_number+'is',float(third_number))
print('complex of '+third_number+' is',complex(third_number))
print('float of '+fourth_number+' is',float(fourth_number))
print('complex of '+fourth_number+' is',complex(fourth_number))
print('float of '+fifth_number+' is',float(fifth_number))
print('complex of '+fifth_number+' is',complex(fifth_number))
